# Tarea 2 de Optimización
Utilizando gradiente descendente, newton y gradiente descendente encontrar los mínimos de diferentes funciones. 

In [5]:
import numpy as np

class Solvers():
    def __init__(self, gradient, matriz_hessiana=np.nan, dif_finite=np.nan, solver="gd", 
                 alpha=0.5, epsilon=np.nan, tol=1e-3, max_iter=1000):
        self.gradient = gradient
        self.matriz_hessiana = matriz_hessiana
        self.alpha = alpha
        self.tol = tol
        self.max_iter = max_iter
        self.solver = solver
        self.epsilon = epsilon
        self.dif_finite = dif_finite
        
    def __gd_solver(self, start_point):
        grad_ = self.gradient(start_point)
        print(grad_)
        convergence = np.dot(grad_, grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        while not stop:
            iter_ += 1
            point = point - self.alpha*grad_
            print("iteration", str(iter_), ", update point ", 
                  str(point[0]), str(point[1]))
            grad_ = self.gradient(point)
            print(grad_)
            stop = ((np.dot(grad_, grad_)) < self.tol) or \
                (iter_>self.max_iter)
        return point 
    
    def __newton(self, start_point):
        grad_ = self.gradient(start_point)
        print(grad_)
        hessiana_ = self.matriz_hessiana(start_point)
        print(hessiana_)
        convergence = np.dot(grad_, grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        while not stop:
            iter_ += 1
            print(grad_@np.linalg.inv(hessiana_))
            point = point-grad_@np.linalg.inv(hessiana_)
            print("iteration", str(iter_), ", update point ", 
                  str(point[0]), str(point[1]))
            grad_ = self.gradient(point)
            print(grad_)
            hessiana_ = self.matriz_hessiana(point)
            print(hessiana_)
            stop = ((np.dot(grad_, grad_)) < self.tol) or \
                (iter_>self.max_iter)
        return point 
    
    def __gd_finite_solver(self, start_point):
        grad_ = self.dif_finite(start_point, self.epsilon)
        print(grad_)
        convergence = np.dot(grad_, grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        while not stop:
            iter_ += 1
            point = point - self.alpha*grad_
            print("iteration", str(iter_), ", update point ", 
                str(point[0]), str(point[1]))
            grad_ = self.dif_finite(point, self.epsilon)
            print(grad_)
            stop = ((np.dot(grad_, grad_)) < self.tol) or \
                    (iter_>self.max_iter)
        return point 
    
    def solve(self, start_point):
        if self.solver=="gd":
            return self.__gd_solver(start_point)
        if self.solver=="nt":
            return self.__newton(start_point)
        if self.solver=="gd_finite":
            return self.__gd_finite_solver(start_point)
        else: 
            raise ValueError('Undefined solver')


### function 1:
$$f(\overrightarrow{x})=10(x_2-x_1^2)+(1-x_1)^2$$

#### a) Gradiente descendente

In [153]:
def function_one(x):
    return np.array([-40*x[0]*(x[1]-x[0]**2)-2*(1-x[0]),
                    20*(x[1]-x[0]**2)])

initial = np.array([0,0])

sol_function_one = Solvers(gradient=function_one, alpha=0.01, max_iter=1000)
print(sol_function_one.solve(initial))

[-2  0]
iteration 1 , update point  0.02 0.0
[-1.95968 -0.008  ]
iteration 2 , update point  0.0395968 8e-05
[-1.91844975 -0.02975813]
iteration 3 , update point  0.05878129746444781 0.00037758131404800005
[-1.87520105 -0.06155319]
iteration 4 , update point  0.0775333079849693 0.0009931132375591797
[-1.82936997 -0.10036601]
iteration 5 , update point  0.09582700764658188 0.0019967733594657647
[-1.78080131 -0.14372084]
iteration 6 , update point  0.11363502073163437 0.0034339817664722242
[-1.72964439 -0.18957872]
iteration 7 , update point  0.13093146467371558 0.005329769000513573
[-1.67626787 -0.23626559]
iteration 8 , update point  0.1476941433883125 0.007692424888731744
[-1.62118736 -0.2824227 ]
iteration 9 , update point  0.16390601693949394 0.010516651909226878
[-1.56500307 -0.32697061]
iteration 10 , update point  0.17955604759520463 0.013786358005175437
[-1.5083467  -0.36908032]
iteration 11 , update point  0.19463951455720846 0.017477161249742627
[-1.45183767 -0.40814759]
itera

iteration 193 , update point  0.8132369747080908 0.6529516070556138
[-0.10018832 -0.1680554 ]
iteration 194 , update point  0.8142388579199036 0.6546321610509647
[-0.09947672 -0.16705513]
iteration 195 , update point  0.8152336251325353 0.6563027123901135
[-0.09877243 -0.16606302]
iteration 196 , update point  0.8162213494229102 0.6579633426214379
[-0.09807534 -0.16507897]
iteration 197 , update point  0.8172021027981566 0.6596141323479016
[-0.09738534 -0.16410289]
iteration 198 , update point  0.8181759562163913 0.661255161241867
[-0.09670234 -0.16313468]
iteration 199 , update point  0.8191429796070007 0.6628865080596148
[-0.09602623 -0.16217426]
iteration 200 , update point  0.8201032418904335 0.6645082506555788
[-0.09535691 -0.16122153]
iteration 201 , update point  0.8210568109975184 0.6661204659963028
[-0.09469429 -0.16027642]
iteration 202 , update point  0.8220037538883203 0.6677232301741252
[-0.09403827 -0.15933882]
iteration 203 , update point  0.8229441365705492 0.6693166184

iteration 286 , update point  0.8831271510188359 0.7748712137576882
[-0.05562421 -0.10084702]
iteration 287 , update point  0.8836833931307431 0.7758796839794797
[-0.05530781 -0.10033311]
iteration 288 , update point  0.8842364712715512 0.7768830150425965
[-0.05499377 -0.09982244]
iteration 289 , update point  0.884786408974364 0.7778812394594302
[-0.05468206 -0.099315  ]
iteration 290 , update point  0.8853332295343376 0.7788743894686943
[-0.05437265 -0.09881076]
iteration 291 , update point  0.885876956011852 0.7798624970384954
[-0.05406552 -0.09830968]
iteration 292 , update point  0.8864176112356302 0.7808455938693613
[-0.05376066 -0.09781175]
iteration 293 , update point  0.886955217805804 0.7818237113972252
[-0.05345803 -0.09731694]
iteration 294 , update point  0.88748979809693 0.7827968807963683
[-0.05315762 -0.09682522]
iteration 295 , update point  0.8880213742609561 0.7837651329823205
[-0.0528594  -0.09633656]
iteration 296 , update point  0.888549968230139 0.784728498614719

iteration 408 , update point  0.9329901606396567 0.8676663943676332
[-0.02936634 -0.05608491]
iteration 409 , update point  0.9332838240494831 0.868227243464189
[-0.02922364 -0.05582906]
iteration 410 , update point  0.9335760604828157 0.8687855340178365
[-0.02908177 -0.05557453]
iteration 411 , update point  0.9338668781870525 0.869341279355592
[-0.02894072 -0.05532134]
iteration 412 , update point  0.9341562853491756 0.8698944927194399
[-0.02880047 -0.05506945]
iteration 413 , update point  0.9344442900963219 0.870445187267026
[-0.02866104 -0.05481888]
iteration 414 , update point  0.9347309004963461 0.8709933760723446
[-0.02852241 -0.05456961]
iteration 415 , update point  0.9350161245583771 0.8715390721264177
[-0.02838457 -0.05432162]
iteration 416 , update point  0.9352999702333684 0.8720822883379674
[-0.02824752 -0.05407492]
iteration 417 , update point  0.9355824454146419 0.8726230375340819
[-0.02811125 -0.05382949]
iteration 418 , update point  0.9358635579384245 0.873161332460

iteration 502 , update point  0.9553051245974591 0.9107629588846494
[-0.01889121 -0.03689844]
iteration 503 , update point  0.9554940366536011 0.9111319433241529
[-0.01880564 -0.03673822]
iteration 504 , update point  0.9556820930110717 0.911499325475441
[-0.0187205  -0.03657875]
iteration 505 , update point  0.9558692980517215 0.9118651129607573
[-0.01863581 -0.03642004]
iteration 506 , update point  0.9560556561303868 0.912229313360184
[-0.01855154 -0.03626209]
iteration 507 , update point  0.9562411715750976 0.9125919342119281
[-0.01846771 -0.03610488]
iteration 508 , update point  0.9564258486872845 0.9129529830126055
[-0.01838431 -0.03594842]
iteration 509 , update point  0.9566096917419833 0.9133124672175229
[-0.01830132 -0.0357927 ]
iteration 510 , update point  0.9567927049880373 0.9136703942409568
[-0.01821877 -0.03563772]
iteration 511 , update point  0.9569748926482982 0.9140267714564304
[-0.01813663 -0.03548347]
iteration 512 , update point  0.9571562589198249 0.91438160619

#### b) Netwon's Method

In [154]:
def hessiana_one(x):
    return np.array([[-40*x[1]+120*(x[0]**2)+2, -40*x[0]],
                    [-40*x[0], 20]])

sol_function_one = Solvers(gradient=function_one, max_iter=5,
                          matriz_hessiana=hessiana_one, solver="nt")
print(sol_function_one.solve(initial))

[-2  0]
[[ 2  0]
 [ 0 20]]
[-1.  0.]
iteration 1 , update point  1.0 0.0
[ 40. -20.]
[[122. -40.]
 [-40.  20.]]
[ 0. -1.]
iteration 2 , update point  1.0 1.0000000000000002
[-8.8817842e-15  4.4408921e-15]
[[ 82. -40.]
 [-40.  20.]]
[1. 1.]


#### c) Gradient descent finite difference

In [155]:
def diference_finite_one(x, epsilon):
    return np.array([(10*(x[1]-(x[0]+epsilon)**2)**2+(1-x[0]-epsilon)**2-(10*(x[1]-(x[0])**2)**2+(1-x[0])**2))/epsilon,
                    (10*(x[1]+epsilon-(x[0])**2)**2+(1-x[0])**2-(10*(x[1]-(x[0])**2)**2+(1-x[0])**2))/epsilon])

sol_function_one = Solvers(gradient=np.nan, alpha=0.01, max_iter=500, dif_finite=diference_finite_one, 
                           epsilon=.05, solver="gd_finite")
print(sol_function_one.solve(initial))

[-1.94875  0.5    ]
iteration 1 , update point  0.019487500000000015 -0.004999999999999983
[-1.89749344  0.39240475]
iteration 2 , update point  0.03846243437040706 -0.008924047468749974
[-1.83861115  0.29193187]
iteration 3 , update point  0.05684854587498622 -0.011843366203460404
[-1.77354946  0.19849753]
iteration 4 , update point  0.07458404049751019 -0.013828341529148247
[-1.70375611  0.11217759]
iteration 5 , update point  0.09162160160843584 -0.014950117403931752
[-1.63065605  0.03310729]
iteration 6 , update point  0.10792816211466165 -0.01528119034688642
[-1.55561538 -0.03859357]
iteration 7 , update point  0.12348431587767339 -0.014895254642019396
[-1.47990193 -0.10287262]
iteration 8 , update point  0.13828333515340266 -0.013866528460060113
[-1.40464952 -0.15977618]
iteration 9 , update point  0.15232983038130068 -0.012268766611818438
[-1.33083074 -0.20946288]
iteration 10 , update point  0.16563813776701491 -0.010174137844655573
[-1.25924092 -0.25220261]
iteration 11 , upda

In [156]:
def function_one(x):
    return 10*(x[1]-x[0]**2)**2+(1-x[0])**2

In [157]:
res_gd = np.array([0.96569466, 0.93115914])
res_nt = np.array([1., 1.])
res_gd_finite = np.array([0.46611116, 0.19110887])

print(function_one(res_gd))
print(function_one(res_nt))
print(function_one(res_gd_finite))

0.0011966538654886046
0.0
0.29187590732030644


### function 2:
$$f(\overrightarrow{x})=30+\sum_{j=1}^2(x_i^2+10\cos (2\pi x_i))$$

In [158]:
def function_two(x):
    return np.array([2*x[0]-20*(np.pi)*np.sin(2*np.pi*x[0]),
                     2*x[1]-20*(np.pi)*np.sin(2*np.pi*x[1])])

initial_two = np.array([0.00, 0.00])
sol_function_two = Solvers(gradient=function_two, alpha=0.01, max_iter=5)
print(sol_function_two.solve(initial_two))

[0. 0.]
[0. 0.]


In [159]:
def hessiana_two(x):
    return np.array([[2-40*(np.pi**2)*np.sin(2*np.pi*x[0]), 0],
                    [0, 2-40*(np.pi**2)*np.sin(2*np.pi*x[1])]])

sol_function_two = Solvers(gradient=function_two, max_iter=5,
                          matriz_hessiana=hessiana_two, solver="nt")
print(sol_function_two.solve(initial))

[0. 0.]
[[2. 0.]
 [0. 2.]]
[0 0]


In [160]:
def diference_finite_two(x, epsilon):
    return np.array([(x[0]+epsilon)**2-10*np.cos(2*np.pi*(x[0]+epsilon))-(x[0]**2-10*np.cos(2*np.pi*x[0])),
                    (x[1]+epsilon)**2-10*np.cos(2*np.pi*(x[1]+epsilon))-(x[1]**2-10*np.cos(2*np.pi*x[1]))])
sol_function_two = Solvers(gradient=np.nan, alpha=0.01, max_iter=500, dif_finite=diference_finite_two, 
                           epsilon=.05, solver="gd_finite")
print(sol_function_two.solve(initial))

[0.49193484 0.49193484]
iteration 1 , update point  -0.004919348370484649 -0.004919348370484649
[0.39570972 0.39570972]
iteration 2 , update point  -0.008876445574457624 -0.008876445574457624
[0.31802947 0.31802947]
iteration 3 , update point  -0.0120567402780563 -0.0120567402780563
[0.25545429 0.25545429]
iteration 4 , update point  -0.01461128321863141 -0.01461128321863141
[0.20511667 0.20511667]
iteration 5 , update point  -0.01666244994840497 -0.01666244994840497
[0.16465948 0.16465948]
iteration 6 , update point  -0.018309044753464825 -0.018309044753464825
[0.13216205 0.13216205]
iteration 7 , update point  -0.01963066528483063 -0.01963066528483063
[0.10606802 0.10606802]
iteration 8 , update point  -0.02069134545661923 -0.02069134545661923
[0.08512063 0.08512063]
iteration 9 , update point  -0.021542551765706824 -0.021542551765706824
[0.06830738 0.06830738]
iteration 10 , update point  -0.02222562558576669 -0.02222562558576669
[0.0548137 0.0548137]
iteration 11 , update point  -0

In [163]:
def function_two(x):
    return 30+x[0]**2-10*np.cos(2*np.pi*x[0])+x[1]**2-10*np.cos(2*np.pi*x[1])

res_gd = np.array([0., 0.])
res_nt = np.array([0., 0.])
res_gd_finite = np.array([-0.02407704, -0.02407704])

print(function_two(res_gd))
print(function_two(res_nt))
print(function_two(res_gd_finite))

10.0
10.0
10.229581183159134


### function three
$$f(\overrightarrow{x})=(x_1+2x_2-7)^2+(2x_1+x_2-5)^2$$

In [174]:
def function_three(x):
    return np.array([2*(x[0]+2*x[1]-7)+4*(2*x[0]+x[1]-5),
                    4*(x[0]+2*x[1]-7)+2*(2*x[0]+x[1]-5)])

sol_function_three = Solvers(gradient=function_three, alpha=0.01, max_iter=500)
print(sol_function_three.solve(initial))

[-34 -38]
iteration 1 , update point  0.34 0.38
[-27.56 -31.48]
iteration 2 , update point  0.6156 0.6948000000000001
[-22.2856 -26.1272]
iteration 3 , update point  0.8384560000000001 0.956072
[-17.966864 -21.731632]
iteration 4 , update point  1.0181246400000001 1.17338832
[-14.43164704 -18.12111968]
iteration 5 , update point  1.1624411104 1.3545995168
[-11.53879276 -15.15447595]
iteration 6 , update point  1.277829038016 1.506144276288
[ -9.17255541 -12.71592493]
iteration 7 , update point  1.36955459211136 1.63330352561792
[ -7.23802587 -10.71052801]
iteration 8 , update point  1.4419348508507905 1.7404088056872191
[-5.65738105 -9.06043314]
iteration 9 , update point  1.498508661310734 1.831013137050434
[-4.36680829 -7.70179934]
iteration 10 , update point  1.5421767442156258 1.9080311304405317
[-3.31398351 -6.58227474]
iteration 11 , update point  1.5753165793588206 1.9738538778592285
[-2.45600318 -5.65892859]
iteration 12 , update point  1.5998766111942002 2.0304431637246
[-1.75

iteration 97 , update point  1.1409059444607632 2.8590940380808676
[ 0.28181175 -0.28181206]
iteration 98 , update point  1.1380878269682175 2.8619121587159198
[ 0.27617554 -0.2761758 ]
iteration 99 , update point  1.1353260715741222 2.86467391668687
[ 0.27065205 -0.27065226]
iteration 100 , update point  1.1326195510817605 2.8673804392922535
[ 0.26523903 -0.2652392 ]
iteration 101 , update point  1.1299671608302042 2.8700328312764873
[ 0.25993426 -0.2599344 ]
iteration 102 , update point  1.1273678182450648 2.872632175282422
[ 0.25473558 -0.2547357 ]
iteration 103 , update point  1.1248204623979645 2.875179532294575
[ 0.24964088 -0.24964098]
iteration 104 , update point  1.122324053574602 2.8776759420732803
[ 0.24464807 -0.24464815]
iteration 105 , update point  1.1198775728512793 2.880122423579984
[ 0.23975512 -0.23975518]
iteration 106 , update point  1.1174800216797527 2.8825199753938833
[ 0.23496002 -0.23496007]
iteration 107 , update point  1.1151304214802669 2.884869576120115
[ 

In [173]:
def hessiana_three(x):
    return np.array([[10, 8],
                    [8, 10]])

sol_function_three = Solvers(gradient=function_three, max_iter=5,
                          matriz_hessiana=hessiana_three, solver="nt")
print(sol_function_three.solve(initial))

[-34 -38]
[[10  8]
 [ 8 10]]
[-1. -3.]
iteration 1 , update point  0.9999999999999982 2.999999999999999
[-2.48689958e-14 -2.30926389e-14]
[[10  8]
 [ 8 10]]
[1. 3.]


In [176]:
def diference_finite_three(x, epsilon):
    return np.array([((x[0]+epsilon+2*x[1]-7)**2+(2*(x[0]+epsilon)+x[1]-5)**2)-((x[0]+2*x[1]-7)**2+(2*x[0]+x[1]-5)**2),
                    ((x[0]+2*(x[1]+epsilon)-7)**2+(2*x[0]+x[1]+epsilon-5)**2)-((x[0]+2*x[1]-7)**2+(2*x[0]+x[1]-5)**2)])
sol_function_three = Solvers(gradient=np.nan, alpha=0.01, max_iter=1000, dif_finite=diference_finite_three, 
                           epsilon=.05, solver="gd_finite")
print(sol_function_three.solve(initial))

[-1.6875 -1.8875]
iteration 1 , update point  0.016875 0.01887499999999989
[-1.6715125 -1.8713125]
iteration 2 , update point  0.033590125000000054 0.03758812499999991
[-1.65566969 -1.85526989]
iteration 3 , update point  0.050146821875000136 0.05614082387499977
[-1.63997026 -1.83937086]
iteration 4 , update point  0.06654652447012523 0.07453453246812487
[-1.62441292 -1.82361412]
iteration 5 , update point  0.08279065371790209 0.09277067370790364
[-1.6089964 -1.8079984]
iteration 6 , update point  0.09888061775448106 0.11085065772449257
[-1.59371943 -1.79252242]
iteration 7 , update point  0.11481781203481076 0.12877588196485223
[-1.57858074 -1.77718493]
iteration 8 , update point  0.13060361944677723 0.14654773130688883
[-1.5635791  -1.76198469]
iteration 9 , update point  0.14623941042431568 0.1641675781725671
[-1.54871326 -1.74692045]
iteration 10 , update point  0.161726543059504 0.1816367826400071
[-1.53398202 -1.73199099]
iteration 11 , update point  0.1770663632136464 0.19895669

iteration 104 , update point  1.111643424896436 1.3092866175766884
[-0.60796364 -0.78819932]
iteration 105 , update point  1.1177230613016471 1.3171686107892193
[-0.60177103 -0.78182647]
iteration 106 , update point  1.123740771551982 1.3249868754900667
[-0.59563486 -0.77551025]
iteration 107 , update point  1.1296971201922619 1.3327419780264085
[-0.58955465 -0.76925016]
iteration 108 , update point  1.135592666679195 1.3404344796555074
[-0.58352987 -0.76304569]
iteration 109 , update point  1.1414279654271768 1.348064936590513
[-0.57756004 -0.75689635]
iteration 110 , update point  1.147203565853679 1.355633900045852
[-0.57164466 -0.75080162]
iteration 111 , update point  1.1529200124242271 1.3631419162822078
[-0.56578323 -0.74476104]
iteration 112 , update point  1.1585778446969772 1.3705895266511
[-0.55997527 -0.7387741 ]
iteration 113 , update point  1.164177597366888 1.3779772676390565
[-0.55422029 -0.73284033]
iteration 114 , update point  1.1697198003094973 1.3853056709113936
[-

iteration 223 , update point  1.5216349786983092 1.9215838148001507
[-0.15804898 -0.3180541 ]
iteration 224 , update point  1.523215468545617 1.9247643558113567
[-0.15598652 -0.31583163]
iteration 225 , update point  1.5247753337796435 1.9279226721581175
[-0.15394326 -0.31362853]
iteration 226 , update point  1.5263147664221128 1.9310589574622083
[-0.15191903 -0.31144461]
iteration 227 , update point  1.5278339567601535 1.9341734036092089
[-0.14991366 -0.30927972]
iteration 228 , update point  1.529333093361916 1.9372662007641221
[-0.14792697 -0.30713366]
iteration 229 , update point  1.53081236309205 1.9403375373868539
[-0.1459588  -0.30500629]
iteration 230 , update point  1.5322719511270424 1.9433876002475514
[-0.14400898 -0.30289742]
iteration 231 , update point  1.533712040970417 1.9464165744418056
[-0.14207735 -0.3008069 ]
iteration 232 , update point  1.5351328144677978 1.949424643405715
[-0.14016374 -0.29873455]
iteration 233 , update point  1.536534451821836 1.9524119889308151

iteration 338 , update point  1.605667035056664 2.1795176596990955
[-0.01285942 -0.15547436]
iteration 339 , update point  1.6057956292425843 2.1810724032603734
[-0.01217322 -0.15464555]
iteration 340 , update point  1.60591736148333 2.182618858727101
[-0.01149378 -0.15382363]
iteration 341 , update point  1.606032299241005 2.1841570949875324
[-0.01082101 -0.15300853]
iteration 342 , update point  1.6061405093648498 2.1856871803156306
[-0.01015487 -0.15220021]
iteration 343 , update point  1.606242058096763 2.187209182376593
[-0.0094953  -0.15139859]
iteration 344 , update point  1.6063370110767727 2.188723168232323
[-0.00884223 -0.15060361]
iteration 345 , update point  1.6064254333484596 2.1902292043468545
[-0.0081956  -0.14981522]
iteration 346 , update point  1.6065073893643298 2.1917273565917266
[-0.00755536 -0.14903337]
iteration 347 , update point  1.6065829429911413 2.1932176902513105
[-0.00692145 -0.14825798]
iteration 348 , update point  1.6066521575151804 2.1947002700280893


iteration 458 , update point  1.586910000141603 2.322104914540613
[ 0.03479697 -0.09168354]
iteration 459 , update point  1.5865620304827326 2.3230217499673436
[ 0.03498972 -0.09136431]
iteration 460 , update point  1.5862121333304495 2.3239353930955757
[ 0.03518022 -0.09104745]
iteration 461 , update point  1.585860331091415 2.324845867596776
[ 0.03536851 -0.09073293]
iteration 462 , update point  1.585506645965571 2.3257531969344263
[ 0.0355546  -0.09042074]
iteration 463 , update point  1.5851510999480054 2.326657404365892
[ 0.03573851 -0.09011086]
iteration 464 , update point  1.5847937148308018 2.3275585129442704
[ 0.03592026 -0.08980326]
iteration 465 , update point  1.5844345122048706 2.328456545520226
[ 0.03609987 -0.08949792]
iteration 466 , update point  1.5840735134617654 2.3293515247438052
[ 0.03627737 -0.08919483]
iteration 467 , update point  1.5837107397954813 2.3302434730662394
[ 0.03645276 -0.08889397]
iteration 468 , update point  1.583346212204239 2.3311324127417263


[ 0.04550746 -0.06939001]
iteration 555 , update point  1.546875314477588 2.399049570493785
[ 0.04555749 -0.06922509]
iteration 556 , update point  1.5464197396232249 2.3997418213834054
[ 0.0456066  -0.06906119]
iteration 557 , update point  1.5459636736395752 2.4004324333179956
[ 0.04565481 -0.06889831]
iteration 558 , update point  1.5455071255381054 2.4011214164568475
[ 0.04570213 -0.06873644]
iteration 559 , update point  1.5450501042445874 2.4018087808724107
[ 0.04574856 -0.06857557]
iteration 560 , update point  1.5445926185998748 2.40249453655107
[ 0.04579412 -0.06841568]
iteration 561 , update point  1.5441346773606712 2.403178693393915
[ 0.04583882 -0.06825678]
iteration 562 , update point  1.5436762892002922 2.4038612612175028
[ 0.04588265 -0.06809885]
iteration 563 , update point  1.5432174627094208 2.404542249754614
[ 0.04592563 -0.06794189]
iteration 564 , update point  1.5427582063968552 2.4052216686550034
[ 0.04596777 -0.06778588]
iteration 565 , update point  1.54229852

[ 0.04675559 -0.05412879]
iteration 685 , update point  1.4859692507830147 2.4781342646095124
[ 0.04673833 -0.05404517]
iteration 686 , update point  1.4855018674706615 2.478674716283333
[ 0.04672082 -0.05396189]
iteration 687 , update point  1.485034659268175 2.4792143352320335
[ 0.04670306 -0.05387897]
iteration 688 , update point  1.484567628630906 2.4797531249188007
[ 0.04668506 -0.05379639]
iteration 689 , update point  1.4841007779880762 2.480291088779683
[ 0.04666682 -0.05371414]
iteration 690 , update point  1.483634109743017 2.4808282302238323
[ 0.04664835 -0.05363224]
iteration 691 , update point  1.4831676262734066 2.481364552633741
[ 0.04662963 -0.05355067]
iteration 692 , update point  1.4827013299315046 2.4819000593654788
[ 0.04661069 -0.05346944]
iteration 693 , update point  1.4822352230443852 2.4824347537489255
[ 0.04659151 -0.05338853]
iteration 694 , update point  1.4817693079141676 2.4829686390880035
[ 0.04657211 -0.05330796]
iteration 695 , update point  1.48130358

[ 0.04345616 -0.04592542]
iteration 806 , update point  1.4312126248813586 2.538290660922566
[ 0.04342258 -0.04586962]
iteration 807 , update point  1.4307783991132614 2.538749357118428
[ 0.04338894 -0.04581396]
iteration 808 , update point  1.4303445096892213 2.5392074967363825
[ 0.04335525 -0.04575845]
iteration 809 , update point  1.4299109571538298 2.539665081213944
[ 0.04332151 -0.04570308]
iteration 810 , update point  1.4294777420432048 2.540122111979259
[ 0.04328772 -0.04564785]
iteration 811 , update point  1.4290448648850718 2.5405785904511897
[ 0.04325387 -0.04559276]
iteration 812 , update point  1.4286123261988417 2.5410345180393934
[ 0.04321997 -0.04553781]
iteration 813 , update point  1.42818012649569 2.5414898961444012
[ 0.04318602 -0.045483  ]
iteration 814 , update point  1.4277482662786338 2.5419447261576966
[ 0.04315202 -0.04542833]
iteration 815 , update point  1.42731674604261 2.5423990094617936
[ 0.04311798 -0.0453738 ]
iteration 816 , update point  1.4268855662

[ 0.04036706 -0.04148148]
iteration 894 , update point  1.394331059344218 2.5766640609272025
[ 0.04033115 -0.04143555]
iteration 895 , update point  1.3939277478037881 2.5770784163851896
[ 0.04029524 -0.04138969]
iteration 896 , update point  1.3935247953992285 2.5774923133120486
[ 0.04025932 -0.04134393]
iteration 897 , update point  1.3931222021689842 2.5779057525638915
[ 0.0402234  -0.04129824]
iteration 898 , update point  1.3927199681478837 2.578318734992396
[ 0.04018748 -0.04125265]
iteration 899 , update point  1.3923180933671746 2.5787312614448425
[ 0.04015155 -0.04120713]
iteration 900 , update point  1.3919165778545595 2.5791433327641498
[ 0.04011562 -0.0411617 ]
iteration 901 , update point  1.39151542163423 2.579554949788911
[ 0.04007969 -0.04111636]
iteration 902 , update point  1.3911146247269033 2.5799661133534295
[ 0.04004376 -0.04107109]
iteration 903 , update point  1.390714187149855 2.5803768242877547
[ 0.04000782 -0.04102591]
iteration 904 , update point  1.39031410

iteration 998 , update point  1.3543034181025373 2.617439577743733
[ 0.03662754 -0.03705884]
iteration 999 , update point  1.3539371427010496 2.617810166182604
[ 0.03659264 -0.03702006]
iteration 1000 , update point  1.353571216322814 2.6181803667808867
[ 0.03655775 -0.03698133]
iteration 1001 , update point  1.3532056387740763 2.618550180081691
[ 0.03652289 -0.03694265]
[1.35320564 2.61855018]


In [178]:
def function_three(x):
    return (x[0]+2*x[1]-7)**2+(2*x[0]+x[1]-5)**2

res_gd = np.array([1.01105134, 2.98894866])
res_nt = np.array([1., 3.])
res_gd_finite = np.array([1.35320564, 2.61855018])

print(function_three(res_gd))
print(function_three(res_nt))
print(function_three(res_gd_finite))

0.00024426423159119355
0.0
0.27344912412133215


### function four
$$f(\overrightarrow{x})=0.25(x_1^2+x_2^2)-0.5(x_1 x_2)$$

In [180]:
def function_four(x):
    return np.array([0.5*x[0]-0.5*x[1], 0.5*x[1]-0.5*x[0]])

sol_function_four = Solvers(gradient=function_four, alpha=0.01, max_iter=500)
print(sol_function_four.solve(initial))

[0. 0.]
[0 0]


In [200]:
def hessiana_four(x):
    return np.array([[0.5, -0.5],
                    [-0.5, 0.5]])

sol_function_four = Solvers(gradient=function_four, max_iter=5,
                          matriz_hessiana=hessiana_four, solver="nt")
print(sol_function_four.solve(initial))

[0. 0.]
[[ 0.5 -0.5]
 [-0.5  0.5]]
[0 0]


In [183]:
def diference_finite_four(x, epsilon):
    return np.array([0.25*((x[0]+epsilon)**2+x[1]**2)-0.5*(x[0]+epsilon)*x[1]-(0.25*(x[0]**2+x[1]**2)-0.5*x[0]*x[1]),
                    0.25*(x[0]**2+(x[1]+epsilon)**2)-0.5*x[0]*(x[1]+epsilon)-(0.25*(x[0]**2+x[1]**2)-0.5*x[0]*x[1])])
sol_function_four = Solvers(gradient=np.nan, alpha=0.01, max_iter=1000, dif_finite=diference_finite_four, 
                           epsilon=.05, solver="gd_finite")
print(sol_function_four.solve(initial))

[0.000625 0.000625]
[0 0]


In [185]:
x = -1.002214847
y = 0.997780235

mu = 0.6669169479

In [186]:
(1-x)**2+100*(y-x**2)**2

4.013292350299983

In [187]:
x= 1
y=1
(1-x)**2+100*(y-x**2)**2

0

In [192]:
501+np.sqrt(250601)

1001.6006392325123

## Regression Lasso

In [6]:
import itertools 
import pandas as pd
from cvxopt import matrix, solvers

def expand_grid(data_dict):
    """Crear la matriz de las combinaciones de A.
    
    Args:
        data_dict: (p, 2) diccionario con los vectores (-1,1)
    
    return:
        pd.Datafram: (p, 2) matriz A.
    """
    rows = itertools.product(*data_dict.values())
    return pd.DataFrame.from_records(rows, columns=data_dict.keys())

In [149]:
def regression_lasso_qp(X, y, t):
    """
    Estimacion de beta para una regression con regularizacion l1.
    
    Args:
        X: (n,p) np.array, los datos del problema
        y: (n) np.array, variable respuesta
        t: parametro t de regularizacion
        
    return:
        sol["x"]: solución optima encontrada
    """
    n, p = X.shape # tamano de los datos
    
    D = matrix(X.T@X, tc="d") # calculamos la matriz D
    q = matrix(2*y.T@X, tc="d") # calculamos el vector q
    
    a = np.array([-1,1]) # calculamos la matriz A
    aux = {}
    for i in range(p):
        aux["Var{}".format(i)] = a
    A = matrix(np.array(expand_grid(aux)), tc="d")
    
    b0 = matrix(np.repeat(t, 2**p).reshape((2**p)), tc="d") # vector b
    
    sol = solvers.qp(D, q, A, b0) # resolvemos el PQ.
    return print(sol["x"])

In [139]:
from sklearn.datasets import load_boston # cargamos los datos
X, y = load_boston(return_X_y=True)

In [150]:
regression_lasso_qp(X[:,0:2], y, 10)

     pcost       dcost       gap    pres   dres
 0: -1.9668e+05 -1.9680e+05  1e+02  2e-17  5e-17
 1: -1.9668e+05 -1.9669e+05  1e+00  1e-16  2e-17
 2: -1.9668e+05 -1.9668e+05  1e-02  2e-16  2e-17
Optimal solution found.
[-1.16e+00]
[-9.90e-01]

