In [1]:
import pandas as pd
from utils import *

In [4]:
a = list(place_ones(4, 1))

In [44]:
def place_ones(size, count):
    for positions in combinations(range(size), count):
        p = [0] * size

        for i in positions:
            p[i] = 1

        yield p
        
        
def combination_opti(c_ij, f_i, a, y_aux, combi=0):
    cost_optimo = 1e14
    A_opti = np.zeros([len(a),6])
    for i in a:
        for j in a:
            for k in a:
                for l in a:
                    for m in a:
                        for n in a:
                            A = np.array([i,j,k,l,m,n]).T
                            #print(y_aux)
                            #print(A)
                            if len(y_aux)==1:
                                A = A[0]
                                #print(c_ij[y_aux])
                            cost = np.sum(np.multiply(c_ij[y_aux], A))+np.sum(f_i[y_aux])
                                #print("cost:", cost)
                            if cost <=cost_optimo:
                                cost_optimo = cost
                                A_opti = A
    if combi==1:
        return cost_optimo, A_opti
    else:
        return cost_optimo
    
    
    
    
def greedyrandomized(y, c_ij, f_i, p_k, alpha):
    k=0
    y_solution = []
    while len(y_solution)<p_k:
        var_libres = 12-len(y_solution)
        costos = []
        a = list(place_ones(len(y_solution)+1, 1))
        # print("a:", a)
        for inst in y:
            y_aux = y_solution.copy()
            y_aux.append(inst)
            cost_optimo = combination_opti(c_ij, f_i, a, y_aux)
            costos.append(cost_optimo)
         
        print("costos:", costos)
        c_max = np.max(costos)
        c_min = np.min(costos)
        #print("c_max", c_max)
        #print("c_min", c_min)
        lim_sup = c_min+alpha*(c_max-c_min)
        #print("lim:", alpha)
        RL = np.concatenate(np.argwhere(costos <= lim_sup))
        print(RL)
        rand = np.random.choice(RL, 1)
        #print(rand)
        y_solution.append(y[rand[0]])
        print("Instacias seleccionadas", np.array(y_solution)+1)
        #print(len(y_solution))
        print("Costo optimo de las instacias selecionadas.", costos[rand[0]])
        y.remove(y[rand[0]])
    return y_solution


def grasp(y, c_ij, f_i, p_k, alpha):
    y_opt = greedyrandomized(y, c_ij, f_i, p_k, alpha)
        
    a = list(place_ones(len(y_opt), 1))
    A_opti = np.zeros([4,6])
    cost_final, A_opti = combination_opti(c_ij, f_i, a, y_opt, 1)
    print("---------------------------------------------------------")
    print("---------------------------------------------------------")
    print("---------------------------------------------------------")

    print("Las instalaciones que se tiene que abrir son", np.array(y_opt)+1)
    print("Las asignaciones de las instalaciones clientes son:")
    print(np.array(A_opti))
    print("El costo final es:", cost_final)
    return 0

In [11]:
from itertools import product

In [46]:
a = list(place_ones(2, 1))
a

[[1, 0], [0, 1]]

In [60]:
A

[[1, 0, 0], [1, 0, 0], [1, 0, 0]]

In [69]:
def combination_opti(c_ij, f_i, a, y_aux, combi=0):
    cost_optimo = 1e14
    A_opti = np.zeros([len(a),6])
    for i in a:
        
    if combi==1:
        return cost_optimo, A_opti
    else:
        return cost_optimo

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [63]:
import itertools

def I(n,m):
    A = []
    for i in range(n):
        A.append([1 if j == i+1  else 0 for j in range(m)])
    return A

#tests:

A = I(3,6)

for m in itertools.permutations(A):
    print('\n'.join(str(row) for row in m))
    print('')

[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]

[0, 1, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 0, 1, 0, 0, 0]

[0, 0, 1, 0, 0, 0]
[0, 1, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0]

[0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 0, 0]

[0, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]

[0, 0, 0, 1, 0, 0]
[0, 0, 1, 0, 0, 0]
[0, 1, 0, 0, 0, 0]



In [34]:
for i in permutations(A):
    print(i)

(array([1, 0, 0, 0]), array([0, 0, 0, 1]))
(array([0, 0, 0, 1]), array([1, 0, 0, 0]))


In [41]:
np.array([i,j])

array([[1, 0, 0, 0],
       [1, 0, 0, 0]])

In [50]:
count=0
for i,j,k,l in product(permutations(a),permutations(a), permutations(a), permutations(a)):
    print([i,j,k,l])
print(count)

[([1, 0], [0, 1]), ([1, 0], [0, 1]), ([1, 0], [0, 1]), ([1, 0], [0, 1])]
[([1, 0], [0, 1]), ([1, 0], [0, 1]), ([1, 0], [0, 1]), ([0, 1], [1, 0])]
[([1, 0], [0, 1]), ([1, 0], [0, 1]), ([0, 1], [1, 0]), ([1, 0], [0, 1])]
[([1, 0], [0, 1]), ([1, 0], [0, 1]), ([0, 1], [1, 0]), ([0, 1], [1, 0])]
[([1, 0], [0, 1]), ([0, 1], [1, 0]), ([1, 0], [0, 1]), ([1, 0], [0, 1])]
[([1, 0], [0, 1]), ([0, 1], [1, 0]), ([1, 0], [0, 1]), ([0, 1], [1, 0])]
[([1, 0], [0, 1]), ([0, 1], [1, 0]), ([0, 1], [1, 0]), ([1, 0], [0, 1])]
[([1, 0], [0, 1]), ([0, 1], [1, 0]), ([0, 1], [1, 0]), ([0, 1], [1, 0])]
[([0, 1], [1, 0]), ([1, 0], [0, 1]), ([1, 0], [0, 1]), ([1, 0], [0, 1])]
[([0, 1], [1, 0]), ([1, 0], [0, 1]), ([1, 0], [0, 1]), ([0, 1], [1, 0])]
[([0, 1], [1, 0]), ([1, 0], [0, 1]), ([0, 1], [1, 0]), ([1, 0], [0, 1])]
[([0, 1], [1, 0]), ([1, 0], [0, 1]), ([0, 1], [1, 0]), ([0, 1], [1, 0])]
[([0, 1], [1, 0]), ([0, 1], [1, 0]), ([1, 0], [0, 1]), ([1, 0], [0, 1])]
[([0, 1], [1, 0]), ([0, 1], [1, 0]), ([1, 0], [0, 1

In [45]:
datos = pd.read_excel("../Tarea CO - Instancias.xlsx", header=None)
c_ij = datos[[0,1,2,3,4,5]].to_numpy()
f_i = datos[6].to_numpy()

y = [i for i in range(0,11)]
grasp(y, c_ij, f_i, 4,0.1)

costos: [280, 294, 338, 277, 315, 370, 189, 335, 205, 233, 243]
[6 8]
Instacias seleccionadas [7]
Costo optimo de las instacias selecionadas. 189
costos: [395, 408, 462, 381, 417, 476, 465, 332, 348, 343]
[7 9]
Instacias seleccionadas [7 9]
Costo optimo de las instacias selecionadas. 332
costos: [545, 557, 611, 524, 561, 623, 615, 491, 486]
[7 8]
Instacias seleccionadas [ 7  9 11]
Costo optimo de las instacias selecionadas. 486
costos: [699, 711, 765, 678, 715, 777, 769, 645]
[7]
Instacias seleccionadas [ 7  9 11 10]
Costo optimo de las instacias selecionadas. 645
---------------------------------------------------------
---------------------------------------------------------
---------------------------------------------------------
Las instalaciones que se tiene que abrir son [ 7  9 11 10]
Las asignaciones de las instalaciones clientes son:
[[1 0 1 1 0 0]
 [0 1 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]]
El costo final es: 645


0

##  Using library pulp

In [1]:
from pulp import *

In [2]:
# Lists (sets / Array) of Customers and Facilities
Customer = [1,2,3,4,5,6]
Facility = ["Fac-{}".format(i) for i in range(1, 12)]

In [3]:
# Dictionaries of the demands and facilities as well as fixed cost at each facility
fixed_cost = {'Fac-1' : 214, 'Fac-2' : 225, 'Fac-3' : 285,
             "Fac-4":205, "Fac-5":229, "Fac-6":294, "Fac-7":137,
             "Fac-8":292, "Fac-9":155, "Fac-10":166, "Fac-11":154}

In [4]:
# Dictionary of the transportation cost from each facility to all the customers 
transportation_cost = {'Fac-1' : {1:18, 2:1, 3:16, 4:6, 5:10, 6:15},
                       'Fac-2' : {1:3, 2:10, 3:17, 4:13, 5:6, 6:20},
                       'Fac-3' : {1:13, 2:6, 3:12, 4:5, 5:7, 6:10},
                       'Fac-4' : {1:9, 2:14, 3:20, 4:11, 5:16, 6:2},
                       'Fac-5' : {1:13, 2:15, 3:16, 4:12, 5:11, 6:19},
                       'Fac-6' : {1:9, 2:3, 3:16, 4:16, 5:20, 6:12},
                       'Fac-7' : {1:3, 2:7, 3:9, 4:6, 5:12, 6:15},
                       'Fac-8' : {1:2, 2:12, 3:3, 4:7, 5:3, 6:16},
                       'Fac-9' : {1:4, 2:2, 3:11, 4:12, 5:5, 6:16},
                       'Fac-10' : {1:12, 2:7, 3:10, 4:18, 5:12, 6:8},
                       'Fac-11' : {1:9, 2:8, 3:19, 4:18, 5:15, 6:20}
                      }

In [5]:
# Setting the Problem
prob = LpProblem("Capacitated Facility Location Problem", LpMinimize)

/home/enrique/anaconda3/lib/python3.7/site-packages/pulp/pulp.py:1199: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


In [6]:
# Defining our Desicion Variables
use_facility = LpVariable.dicts("Use Facility", Facility, 0, 1, LpBinary)
ser_customer = LpVariable.dicts("Service", [(i,j) for i in Customer for j in Facility], 0)

In [7]:

# Setting the Objective Function
prob += lpSum(fixed_cost[j]*use_facility[j] for j in Facility) + lpSum(transportation_cost[j][i]*ser_customer[(i,j)] for j in Facility for i in Customer)

In [8]:
# Costraints
for i in Customer:
    prob += lpSum(ser_customer[(i,j)] for j in Facility) == 1

for i in Customer:
    for j in Facility:
        prob += ser_customer[(i,j)] <= use_facility[j]
        
prob += lpSum(use_facility[j] for j in Facility) == 4


In [9]:
prob.solve()

1

In [10]:
print("Solution Status = ", LpStatus[prob.status])

Solution Status =  Optimal


In [11]:
# Print the solution of Binary Decision Variables
Tolerance = 0.0001
for j in Facility:
    if use_facility[j].varValue > Tolerance:
        print("Estalish Facility at site = ", j)

Estalish Facility at site =  Fac-7
Estalish Facility at site =  Fac-9
Estalish Facility at site =  Fac-10
Estalish Facility at site =  Fac-11


In [12]:

# Print the solution of Continuous Decision Variables
for v in prob.variables():
    print(v.name, "=", v.varValue)

Service_(1,_'Fac_1') = 0.0
Service_(1,_'Fac_10') = 0.0
Service_(1,_'Fac_11') = 0.0
Service_(1,_'Fac_2') = 0.0
Service_(1,_'Fac_3') = 0.0
Service_(1,_'Fac_4') = 0.0
Service_(1,_'Fac_5') = 0.0
Service_(1,_'Fac_6') = 0.0
Service_(1,_'Fac_7') = 1.0
Service_(1,_'Fac_8') = 0.0
Service_(1,_'Fac_9') = 0.0
Service_(2,_'Fac_1') = 0.0
Service_(2,_'Fac_10') = 0.0
Service_(2,_'Fac_11') = 0.0
Service_(2,_'Fac_2') = 0.0
Service_(2,_'Fac_3') = 0.0
Service_(2,_'Fac_4') = 0.0
Service_(2,_'Fac_5') = 0.0
Service_(2,_'Fac_6') = 0.0
Service_(2,_'Fac_7') = 0.0
Service_(2,_'Fac_8') = 0.0
Service_(2,_'Fac_9') = 1.0
Service_(3,_'Fac_1') = 0.0
Service_(3,_'Fac_10') = 0.0
Service_(3,_'Fac_11') = 0.0
Service_(3,_'Fac_2') = 0.0
Service_(3,_'Fac_3') = 0.0
Service_(3,_'Fac_4') = 0.0
Service_(3,_'Fac_5') = 0.0
Service_(3,_'Fac_6') = 0.0
Service_(3,_'Fac_7') = 1.0
Service_(3,_'Fac_8') = 0.0
Service_(3,_'Fac_9') = 0.0
Service_(4,_'Fac_1') = 0.0
Service_(4,_'Fac_10') = 0.0
Service_(4,_'Fac_11') = 0.0
Service_(4,_'Fac_2')

In [13]:
# Print Optimal
print("Total Cost = ", value(prob.objective))

Total Cost =  645.0
